import { EventDetailComponent } from './event-detail/event-detail.component';
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { EventListComponent } from './event-list/event-list.component';
import { NotFoundComponent } from './not-found/not-found.component';
import { EventRouteActivatorService } from './event-route-activator.service';

// An Angular best practice is to load and configure the router in a separate, top-level module
// that is dedicated to routing and imported by the root AppModule.
// ng generate module app-routing --flat --module=app

// Note that this file was generated by default

const routes: Routes = [
  { path: 'events', component: EventListComponent },
  { path: 'events/:id', component: EventDetailComponent, canActivate: [EventRouteActivatorService] },
  { path: 'not-found', component: NotFoundComponent },
  { path: '', redirectTo: '/events', pathMatch: 'full' },
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule { }
